package org.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Accionista generated by hbm2java
 */
@Entity
@Table(name = "ACCIONISTA", schema = "BDSISTEMAFINANCIERO")
@XmlRootElement(name = "accionista")
@XmlAccessorType(XmlAccessType.NONE)
public class Accionista implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private BigInteger idAccionista;
	private PersonaNatural personaNatural;
	private PersonaJuridica personaJuridica;
	private int porcentajeParticipacion;

	public Accionista() {
	}

	public Accionista(BigInteger idAccionista, PersonaNatural personaNatural, PersonaJuridica personaJuridica, int porcentajeParticipacion) {
		this.idAccionista = idAccionista;
		this.personaNatural = personaNatural;
		this.personaJuridica = personaJuridica;
		this.porcentajeParticipacion = porcentajeParticipacion;
	}

	@XmlElement(name = "id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Id
	@Column(name = "ID_ACCIONISTA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigInteger getIdAccionista() {
		return this.idAccionista;
	}

	public void setIdAccionista(BigInteger idAccionista) {
		this.idAccionista = idAccionista;
	}

	@XmlElement(name = "personaNatural")
	@NotNull
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA_NATURAL", nullable = false)
	public PersonaNatural getPersonaNatural() {
		return this.personaNatural;
	}

	public void setPersonaNatural(PersonaNatural personaNatural) {
		this.personaNatural = personaNatural;
	}

	@XmlTransient
	@NotNull
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA_JURIDICA", nullable = false)
	public PersonaJuridica getPersonaJuridica() {
		return this.personaJuridica;
	}

	public void setPersonaJuridica(PersonaJuridica personaJuridica) {
		this.personaJuridica = personaJuridica;
	}

	@XmlElement(name = "porcentajeParticipacion")
	@NotNull
	@Min(value = 0)
	@Max(value = 100)
	@Column(name = "PORCENTAJE_PARTICIPACION", nullable = false, precision = 5)
	public int getPorcentajeParticipacion() {
		return this.porcentajeParticipacion;
	}

	public void setPorcentajeParticipacion(int porcentajeParticipacion) {
		this.porcentajeParticipacion = porcentajeParticipacion;
	}

}
